/// <reference types="astro/client" />

// Env, Cloudflare.Env, and process.env types are generated by `wrangler types`
// into worker-configuration.d.ts at the repo root (gitignored). Run:
//     npm run cf-typegen
// whenever wrangler.jsonc bindings change.

declare namespace App {
  interface Locals {
    db: import('./db').AppDb;
    auth: import('./lib/auth').AppAuth;
    user: {
      id: string;
      name: string;
      email: string;
      image: string | null | undefined;
      termsAcceptedAt: Date | null;
    } | null;
    session: {
      id: string;
      userId: string;
      token: string;
      expiresAt: Date;
    } | null;
    account: import('./lib/account').AccountContext | null;
  }
}

declare module 'cloudflare:workers' {
  interface ProvidedEnv extends Env {}
}
