/// <reference types="astro/client" />

// Env, Cloudflare.Env, and process.env types are generated by `wrangler types`
// into worker-configuration.d.ts at the repo root (gitignored). Run:
//     npm run cf-typegen
// whenever wrangler.jsonc bindings change.

declare namespace App {
  interface Locals {
    db: import('./db').AppDb;
    auth: import('./lib/auth').AppAuth;
    user: {
      id: string;
      name: string;
      email: string;
      image: string | null | undefined;
      termsAcceptedAt: Date | null;
    } | null;
    session: {
      id: string;
      userId: string;
      token: string;
      expiresAt: Date;
    } | null;
    account: import('./lib/account').AccountContext | null;
  }
}

declare module 'cloudflare:workers' {
  interface ProvidedEnv extends Env {
    /**
     * Cloudflare service binding to @baseout/server (the backup engine).
     * Optional because the binding is declared only in env.staging + env.production
     * of wrangler.jsonc — dev (`wrangler dev --remote`) intentionally has no
     * binding, since `--remote` upload validation would fail without a deployed
     * engine. The route at /api/connections/airtable/test handles undefined
     * by returning 503 server_misconfigured.
     */
    BACKUP_ENGINE?: Fetcher;
    /** Shared secret with @baseout/server's INTERNAL_TOKEN. Sent as x-internal-token header on every call to the engine. */
    BACKUP_ENGINE_INTERNAL_TOKEN: string;
  }
}
