/**
 * Public-email-provider denylist (web-signup-domain-association).
 *
 * Domains here never resolve to any Organization for signup association —
 * possession of a gmail.com address says nothing about company membership.
 *
 * Maintained DATA, not code (design Decision 3): extend this list freely;
 * no logic lives here. Lowercase entries only.
 */

export const PUBLIC_EMAIL_DOMAINS: readonly string[] = [
  // Google
  'gmail.com',
  'googlemail.com',
  // Microsoft
  'outlook.com',
  'outlook.de',
  'outlook.fr',
  'hotmail.com',
  'hotmail.co.uk',
  'hotmail.fr',
  'hotmail.de',
  'live.com',
  'live.co.uk',
  'msn.com',
  // Yahoo
  'yahoo.com',
  'yahoo.co.uk',
  'yahoo.fr',
  'yahoo.co.jp',
  'yahoo.de',
  'ymail.com',
  'rocketmail.com',
  // Apple
  'icloud.com',
  'me.com',
  'mac.com',
  // Proton
  'proton.me',
  'protonmail.com',
  'pm.me',
  // Other global providers
  'aol.com',
  'gmx.com',
  'gmx.de',
  'gmx.net',
  'mail.com',
  'zoho.com',
  'zohomail.com',
  'yandex.com',
  'yandex.ru',
  'fastmail.com',
  'fastmail.fm',
  'hey.com',
  'tutanota.com',
  'tutamail.com',
  'tuta.com',
  'tuta.io',
  'mail.ru',
  'inbox.ru',
  'bk.ru',
  'list.ru',
  'qq.com',
  'foxmail.com',
  '163.com',
  '126.com',
  'yeah.net',
  'sina.com',
  'naver.com',
  'daum.net',
  'hanmail.net',
  // ISP / regional
  'comcast.net',
  'verizon.net',
  'att.net',
  'sbcglobal.net',
  'cox.net',
  'charter.net',
  'earthlink.net',
  'btinternet.com',
  'sky.com',
  'talktalk.net',
  'virginmedia.com',
  'web.de',
  't-online.de',
  'freenet.de',
  'orange.fr',
  'wanadoo.fr',
  'free.fr',
  'laposte.net',
  'sfr.fr',
  'libero.it',
  'virgilio.it',
  'tiscali.it',
  'seznam.cz',
  'wp.pl',
  'o2.pl',
  'interia.pl',
  'onet.pl',
  'uol.com.br',
  'bol.com.br',
  'terra.com.br',
  'rediffmail.com',
  'sify.com',
  'bigpond.com',
  'optusnet.com.au',
  'xtra.co.nz',
  'shaw.ca',
  'rogers.com',
  'sympatico.ca',
  // Disposable-adjacent commons
  'duck.com',
  'mailinator.com',
  'guerrillamail.com',
  '10minutemail.com',
]
