/**
 * Entitlement catalog — master-DB tables (shared-entitlements, design D1–D4).
 *
 * The DB-native replacement for Stripe-metadata capability resolution: plans,
 * their prices, the feature dictionary, and the per-plan value matrix seeded
 * from research/pricing/pricing-guide.md §3. These tables are PURE catalog —
 * no foreign keys to app-owned tables (organizations, subscription_items) — so
 * they live in @baseout/db-schema and are imported directly by web, server, and
 * admin (the account-scoped tables that DO reference organizations live in
 * apps/web/src/db/schema/entitlements.ts, since the package must not depend on
 * the app). Canonical migrations are generated by apps/web's drizzle-kit.
 *
 * Conventions match core.ts: text ids with gen_random_uuid(); created_at /
 * modified_at; snake_case; the shared `baseout` pgSchema from ./auth.
 * Typed values (value_bool / value_numeric / value_enum) follow the entitlement
 * value model in ../entitlements/values.ts (NULL numeric = fair-use sentinel).
 */

import {
  boolean,
  check,
  index,
  integer,
  jsonb,
  numeric,
  text,
  timestamp,
  unique,
} from 'drizzle-orm/pg-core'
import { sql } from 'drizzle-orm'
import { baseout } from './auth'

// ———————————————————————————————————————————————————————————————————————————
// FEATURE GROUPS
// The 7 display groups on the pricing comparison table (pricing-guide §5).
// Display copy only — code never gates on a group.
// ———————————————————————————————————————————————————————————————————————————

export const featureGroups = baseout.table('feature_groups', {
  id: text('id').primaryKey().default(sql`gen_random_uuid()`),
  slug: text('slug').notNull().unique(),
  name: text('name').notNull(),
  sortOrder: integer('sort_order').notNull().default(0),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  modifiedAt: timestamp('modified_at', { withTimezone: true }).notNull().defaultNow(),
})

// ———————————————————————————————————————————————————————————————————————————
// FEATURES
// The typed dictionary of levers. Code gates on `slug`, never on `name` (D3).
// value_type selects which typed column plan_features / overrides populate.
// enum_values is the ordered ladder (index = rank) for enum features.
// meterable + meter_kind link limit features to the metering system (D3).
// ———————————————————————————————————————————————————————————————————————————

export const features = baseout.table('features', {
  id: text('id').primaryKey().default(sql`gen_random_uuid()`),
  groupId: text('group_id')
    .notNull()
    .references(() => featureGroups.id, { onDelete: 'restrict' }),
  slug: text('slug').notNull().unique(),
  name: text('name').notNull(),
  valueType: text('value_type').notNull(), // 'boolean' | 'limit' | 'enum'
  unit: text('unit'), // 'records' | 'gb' | 'credits' | 'calls' | 'count' | 'days' | null
  enumValues: jsonb('enum_values'), // ordered ladder for enum features, else null
  meterable: boolean('meterable').notNull().default(false),
  meterKind: text('meter_kind'), // 'flow' | 'stock' | 'creation' | null
  sortOrder: integer('sort_order').notNull().default(0),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  modifiedAt: timestamp('modified_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  check('features_value_type_check', sql`${table.valueType} in ('boolean', 'limit', 'enum')`),
  check('features_meter_kind_check', sql`${table.meterKind} is null or ${table.meterKind} in ('flow', 'stock', 'creation')`),
  index('features_group_id_idx').on(table.groupId),
])

// ———————————————————————————————————————————————————————————————————————————
// PLANS
// One row per sellable/resolvable plan. kind: public (Lite/Core/Plus/Max),
// trial, custom (Enterprise baseline), legacy. Deactivation flips status to
// 'inactive' (unsellable, still resolvable for existing subscribers) — never
// delete (D4).
// ———————————————————————————————————————————————————————————————————————————

export const plans = baseout.table('plans', {
  id: text('id').primaryKey().default(sql`gen_random_uuid()`),
  slug: text('slug').notNull().unique(), // 'lite' | 'core' | 'plus' | 'max' | 'trial' | 'enterprise'
  name: text('name').notNull(),
  kind: text('kind').notNull(), // 'public' | 'trial' | 'custom' | 'legacy'
  status: text('status').notNull().default('active'), // 'active' | 'inactive'
  stripeProductId: text('stripe_product_id').unique(),
  sortOrder: integer('sort_order').notNull().default(0),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  modifiedAt: timestamp('modified_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  check('plans_kind_check', sql`${table.kind} in ('public', 'trial', 'custom', 'legacy')`),
  check('plans_status_check', sql`${table.status} in ('active', 'inactive')`),
])

// ———————————————————————————————————————————————————————————————————————————
// PLAN PRICES
// Monthly + annual Stripe price references per plan, with cached amounts.
// ———————————————————————————————————————————————————————————————————————————

export const planPrices = baseout.table('plan_prices', {
  id: text('id').primaryKey().default(sql`gen_random_uuid()`),
  planId: text('plan_id')
    .notNull()
    .references(() => plans.id, { onDelete: 'cascade' }),
  billingPeriod: text('billing_period').notNull(), // 'monthly' | 'annual'
  amountCents: integer('amount_cents').notNull(),
  currency: text('currency').notNull().default('usd'),
  stripePriceId: text('stripe_price_id').unique(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  modifiedAt: timestamp('modified_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  check('plan_prices_billing_period_check', sql`${table.billingPeriod} in ('monthly', 'annual')`),
  unique('plan_prices_plan_period_unique').on(table.planId, table.billingPeriod),
])

// ———————————————————————————————————————————————————————————————————————————
// PLAN FEATURES
// The value matrix: one typed value per (plan, feature). Editing a value here
// changes it for every non-overridden subscriber (D4). Exactly one of
// value_bool / value_numeric / value_enum is meaningful, per the feature's
// value_type; a NULL numeric on a limit feature = fair use (values.ts).
// ———————————————————————————————————————————————————————————————————————————

export const planFeatures = baseout.table('plan_features', {
  id: text('id').primaryKey().default(sql`gen_random_uuid()`),
  planId: text('plan_id')
    .notNull()
    .references(() => plans.id, { onDelete: 'cascade' }),
  featureId: text('feature_id')
    .notNull()
    .references(() => features.id, { onDelete: 'cascade' }),
  valueBool: boolean('value_bool'),
  valueNumeric: numeric('value_numeric'),
  valueEnum: text('value_enum'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  modifiedAt: timestamp('modified_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  unique('plan_features_plan_feature_unique').on(table.planId, table.featureId),
  index('plan_features_plan_id_idx').on(table.planId),
])

// ———————————————————————————————————————————————————————————————————————————
// ADD-ON CATALOG
// The locked add-on library (pricing-guide §6) as data. Each add-on extends one
// limit feature by unit_quantity; kind = recurring (monthly) or one_time (pack,
// expires at the monthly anniversary boundary). Purchases reference these rows
// (addon_purchases lives in apps/web — it also references organizations).
// ———————————————————————————————————————————————————————————————————————————

export const addonCatalog = baseout.table('addon_catalog', {
  id: text('id').primaryKey().default(sql`gen_random_uuid()`),
  slug: text('slug').notNull().unique(),
  name: text('name').notNull(),
  featureSlug: text('feature_slug').notNull(), // the limit feature this extends
  unitQuantity: numeric('unit_quantity').notNull(), // e.g. 100000 records, 50 GB, 1000 credits
  kind: text('kind').notNull(), // 'recurring' | 'one_time'
  priceCents: integer('price_cents').notNull(),
  stripePriceId: text('stripe_price_id').unique(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  modifiedAt: timestamp('modified_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  check('addon_catalog_kind_check', sql`${table.kind} in ('recurring', 'one_time')`),
  index('addon_catalog_feature_slug_idx').on(table.featureSlug),
])
