// @baseout/db-schema — Drizzle schema for the master DB.
//
// See openspec/changes/system-db-schema/proposal.md for the full extraction
// plan. The tables are organized by domain in ./schema/*.ts and re-exported
// here. Migrations are generated by drizzle-kit against the *consumer's*
// drizzle.config.ts today (apps/web owns the canonical drizzle/ directory);
// they move into this package as the extraction progresses through Phase 1.
//
// Conventions:
// - snake_case tables/columns
// - text ids with gen_random_uuid() for Better Auth tables; UUID PKs elsewhere
// - created_at / updated_at (Better Auth) or created_at / modified_at (Baseout)
// - _enc suffix for AES-256-GCM-encrypted columns
//
// Runtime apps consume named tables, e.g.
//   import { users, sessions } from '@baseout/db-schema'
// The package is workspace-internal (workspace:*) and exports source `.ts`
// directly so consumers (Astro/Vite, vitest-pool-workers, drizzle-kit) read
// the schema without an intermediate build step. If we ever need to publish
// externally, flip main/types/exports back to ./dist and add the build to CI.

export * from './schema/auth'
