/**
 * THE CHANGELOG'S ENTRY LIST, DERIVED FROM THE COLLECTION.
 *
 * The hub at `/changelog/` shows a count, and one row per entry carrying a date, a reading time and
 * an excerpt. Every one of those is knowable from the entry itself, so none of them is written down
 * twice: the hub reads this, this reads `getCollection('docs')`, and adding a file to
 * `content/docs/changelog/<year>/` is the whole act of publishing an entry. `docs-index.ts` carries
 * the longer version of this argument, and the reason it is a rule here: a hand-written list of
 * pages in this repo has drifted from the pages that exist twice already.
 *
 * THE SIDEBAR IS DERIVED THE SAME WAY BUT NOT BY THIS FILE. `astro.config.mjs` uses Starlight's
 * `autogenerate` over `changelog/`, which turns each year DIRECTORY into a year GROUP. So the two
 * surfaces agree by both reading the filesystem, not by reading each other.
 *
 * WHY THE DATE IS `lastUpdated` AND NOT A FIELD OF OUR OWN. `content.config.ts` carries the story of
 * two frontmatter fields nothing read (`stub`, `provisional`) and the standing rule that came out of
 * it. `lastUpdated` is Starlight's own, already in `docsSchema`, already typed, and the schema parses
 * it whether or not the config renders a last-updated line. Adding `date:` beside it would be a
 * second date on the same page that nothing reconciles.
 *
 * READING TIME IS COMPUTED, NEVER DECLARED, for the plain reason that a declared one is wrong the
 * first time the page is edited. 200 words a minute is the conventional figure and is rounded up, so
 * the shortest entry reads "1 min read" rather than "0".
 */
import { getCollection } from 'astro:content';

export interface ChangelogEntry {
  /** Site-relative URL, with the trailing slash Starlight serves. */
  href: string;
  title: string;
  /** Frontmatter `description`. The excerpt shown on the hub. */
  description: string;
  /** Frontmatter `lastUpdated`, when it is a date. */
  date?: Date;
  /** Whole minutes, at least 1. */
  readingMinutes: number;
}

const WORDS_PER_MINUTE = 200;

const readingMinutes = (body: string): number =>
  Math.max(1, Math.round(body.trim().split(/\s+/).length / WORDS_PER_MINUTE));

/* `lastUpdated` is `Date | boolean | undefined` in Starlight's schema — `true` means "take it from
   git", which a build of this repo would answer with the date the file was committed rather than the
   date the change happened. Only a real date is used, and a missing one sorts last rather than
   throwing: an entry with no date is still an entry, and a hub that 500s because somebody forgot a
   line is a worse failure than a row without a date on it. */
/* EXPORTED because `components/DocsPageTitle.astro` reads the same field off the route and has to
   apply the same guard: two places asking "is this a real date" with two different answers is how a
   page ends up printing `true`. */
export const entryDate = (value: unknown): Date | undefined =>
  value instanceof Date ? value : undefined;

/** Every changelog entry, newest first. The hub page itself is not one of them. */
export async function changelogEntries(): Promise<ChangelogEntry[]> {
  const entries = await getCollection(
    'docs',
    (entry) => entry.id.startsWith('changelog/') && entry.id !== 'changelog/index',
  );

  return entries
    .map((entry) => ({
      href: `/${entry.id}/`,
      title: entry.data.title,
      description: entry.data.description ?? '',
      date: entryDate(entry.data.lastUpdated),
      readingMinutes: readingMinutes(entry.body ?? ''),
    }))
    .sort((a, b) => (b.date?.getTime() ?? 0) - (a.date?.getTime() ?? 0));
}

/** `21 August 2026`. Spelled out because a changelog row is read once, not scanned in a column. */
export const formatEntryDate = (date: Date): string =>
  new Intl.DateTimeFormat('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    timeZone: 'UTC',
  }).format(date);

/**
 * ── THE MONTH GROUPING ──────────────────────────────────────────────────────────────────────────
 * Dan, on video 2026-08-26: "first the year, then the month, if we can go one more level", and on
 * the hub "more grouped by the year and month on this page, be able to dive down into them and
 * newest first".
 *
 * THE MONTH IS DERIVED, NOT FILED. The obvious reading of "one more level" is a directory —
 * `changelog/2026/08/` — because that is what makes Starlight's `autogenerate` produce a nested
 * group. It would also rewrite the URL of every entry that exists, need a redirect for each, and
 * label the group `08`, since an autogenerated group takes the directory's own name and there is no
 * per-directory label option. So the month is computed from the date the entry already carries, and
 * both surfaces group by it: the hub renders the headings itself, `routeData.ts` re-nests the
 * sidebar Starlight built. Files stay where they are and no URL moves.
 *
 * WHAT THE HEADING DOES NOT SAY. Oleh, 2026-08-26, choosing between three readings of Dan's word
 * "deployed": the label is the month and nothing else. The date we hold is `lastUpdated`, which
 * means the entry was last edited then; writing "Deployed August 2026" over it would make a
 * deployment claim out of a field that does not carry one, and `PRODUCT.md` is explicit that every
 * number on screen traces to a real source. A bare month is true whatever the date turns out to
 * mean, and it is what a reader scanning a changelog is looking for anyway.
 */

/** `August 2026`. The month group's label on both surfaces. */
export const formatEntryMonth = (date: Date): string =>
  new Intl.DateTimeFormat('en-GB', { month: 'long', year: 'numeric', timeZone: 'UTC' }).format(date);

/** `2026-08`. Sorts as a string exactly as it sorts as a date, which is the whole reason for it. */
export const monthKey = (date: Date): string =>
  `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, '0')}`;

export interface ChangelogMonth {
  /** `2026-08`, or `''` for the group of entries that carry no date. */
  key: string;
  /** `August 2026`, or `''` — a heading is only rendered where there is a month to name. */
  label: string;
  /** Newest first, in the order they arrived. */
  entries: ChangelogEntry[];
}

/**
 * Entries grouped into months, newest month first.
 *
 * AN UNDATED ENTRY IS STILL AN ENTRY. `changelogEntries` already refuses to throw on a missing date
 * and sorts it last, for the reason stated above: a hub that 500s because somebody forgot a line is
 * the worse failure. Grouping keeps that promise by collecting them into one keyless group which
 * both surfaces render without a heading — inventing a word like "Undated" would be putting a label
 * on a customer surface to describe our own frontmatter.
 */
export function groupByMonth(entries: ChangelogEntry[]): ChangelogMonth[] {
  const months = new Map<string, ChangelogMonth>();

  for (const entry of entries) {
    const key = entry.date ? monthKey(entry.date) : '';
    const month = months.get(key);
    if (month) month.entries.push(entry);
    else
      months.set(key, {
        key,
        label: entry.date ? formatEntryMonth(entry.date) : '',
        entries: [entry],
      });
  }

  /* Descending by key, with the keyless group forced last rather than left to string comparison —
     `''` does sort below `'2026-08'`, but a reader should not have to work that out to know where
     an undated entry lands. */
  return [...months.values()].sort((a, b) => {
    if (a.key === b.key) return 0;
    if (!a.key) return 1;
    if (!b.key) return -1;
    return b.key.localeCompare(a.key);
  });
}

export interface ChangelogPlacement {
  month: ChangelogMonth;
  /** Position in the newest-first order. Lower is newer. */
  rank: number;
}

/**
 * Where each entry belongs, keyed by the LAST SEGMENT of its URL.
 *
 * `routeData.ts` has sidebar links and no frontmatter, so it needs a way back from an href to a
 * date. Keying on the final segment rather than the whole path is what makes the lookup survive a
 * `base` being configured, a trailing slash being dropped, or the year directories being renamed:
 * an entry's slug is unique inside the changelog, which is the only place this map is consulted.
 *
 * THE RANK IS WHY "NEWEST FIRST" IS NOW TRUE OF THE SIDEBAR AS WELL. Dan asked for it on video and
 * the file comment in `astro.config.mjs` claimed it — "ordering inside a year is `sidebar.order` in
 * each entry's frontmatter, newest first" — while the three entries carried `order: 1, 2, 3` against
 * dates of 20, 24 and 21 August. Nothing was wrong with the mechanism; a hand-kept rank had simply
 * drifted from the dates beside it, in the one place nothing tells you it has. So the ranks are
 * gone from the frontmatter and the order is derived from the date, which is the same rule the hub
 * and the reading time already follow: the entry knows this about itself, so nobody writes it down.
 */
export async function changelogPlacementBySlug(): Promise<Map<string, ChangelogPlacement>> {
  const entries = await changelogEntries();
  const months = groupByMonth(entries);
  const rankOf = new Map(entries.map((entry, index) => [entry.href, index]));
  const bySlug = new Map<string, ChangelogPlacement>();

  for (const month of months)
    for (const entry of month.entries) {
      const slug = entry.href.split('/').filter(Boolean).pop();
      if (slug) bySlug.set(slug, { month, rank: rankOf.get(entry.href) ?? Number.MAX_SAFE_INTEGER });
    }

  return bySlug;
}
