/**
 * The docs index, shared by the landing's search-or-ask input and the chat's source citations.
 *
 * PAGEFIND IS BUILD-TIME. `/pagefind/pagefind.js` does not exist under `astro dev` at all — it is
 * generated by the build — so every caller must stay useful without it. Verifying anything that
 * touches this file means `astro build` plus serving `dist/`, never the dev server.
 */

export interface DocHit {
  url: string;
  title: string;
  excerpt: string;
}

/**
 * `{ any: [...] }`, NEVER a bare array. Pagefind ANDs the values of a filter given as an array, so
 * `platform: ['notion', 'all']` asks for documents that are BOTH, which no document is, and the
 * search returns nothing at all — measured against the built index: the array form gave 0 results
 * where the `any` form gave 8. It is the same rule that makes a multi-word Pagefind query an AND
 * of its terms, applied one level up, and it fails silently in exactly the same way.
 */
interface PagefindOptions {
  filters?: Record<string, { any: string[] }>;
}

interface PagefindRaw {
  init: () => Promise<void>;
  search: (
    q: string,
    opts?: PagefindOptions,
  ) => Promise<{ results: { data: () => Promise<{ url: string; meta?: { title?: string }; excerpt: string }> }[] }>;
}

let mod: PagefindRaw | null = null;
/* A FAILED load must be retryable. This was a single sticky `tried` flag: one transient failure —
   a request that lost a race with the page unloading, a hiccup on the wasm fetch — and every later
   query on that page silently returned nothing, for good. Only success is remembered now; failure
   just means the next query tries again. */
let loading: Promise<PagefindRaw | null> | null = null;

async function load(): Promise<PagefindRaw | null> {
  if (mod) return mod;
  if (loading) return loading;
  loading = (async () => {
    /* The specifier is held in a VARIABLE. A literal — even with `@vite-ignore` — is still walked
       by Rollup, which fails the build with "failed to resolve import /pagefind/pagefind.js":
       the file does not exist at bundle time, it is emitted by the Pagefind step afterwards. */
    const src = '/pagefind/pagefind.js';
    try {
      const m = (await import(/* @vite-ignore */ src)) as unknown as PagefindRaw;
      await m.init();
      mod = m;
      return m;
    } catch {
      return null; // Expected under `astro dev`; retried on the next query elsewhere.
    } finally {
      loading = null;
    }
  })();
  return loading;
}

/**
 * Returns [] rather than throwing — a missing index must degrade, never break the caller.
 *
 * `platforms` narrows to the reader's chosen set. It is passed through with `all` appended, which
 * is the value every platform-neutral page carries (`components/DocsPageTitle.astro` emits it):
 * Pagefind ORs the values of one filter, so `['notion', 'all']` reads as "Notion pages, plus
 * everything true of any platform" — the same rule the sidebar applies to its rows. Omit it, or
 * pass the full set, and no filter is sent at all: filtering to everything is not filtering, and
 * sending it anyway would drop any page the build failed to tag.
 */
export async function searchDocs(
  query: string,
  limit: number,
  platforms?: string[],
): Promise<DocHit[]> {
  const pf = await load();
  if (!pf) return [];
  try {
    const narrowed =
      platforms && platforms.length ? { platform: { any: [...platforms, 'all'] } } : undefined;
    const res = await pf.search(query, narrowed ? { filters: narrowed } : undefined);
    const top = await Promise.all(res.results.slice(0, limit).map((r) => r.data()));
    return top.map((d) => ({ url: d.url, title: d.meta?.title ?? d.url, excerpt: d.excerpt }));
  } catch {
    return [];
  }
}

/** Whether the index is actually available — callers use it to explain an empty result honestly. */
export async function indexAvailable(): Promise<boolean> {
  return (await load()) !== null;
}
